package shordinger.wrapper.net.minecraft.util.datafix;

import shordinger.wrapper.net.minecraft.block.BlockJukebox;
import shordinger.wrapper.net.minecraft.entity.Entity;
import shordinger.wrapper.net.minecraft.entity.boss.EntityDragon;
import shordinger.wrapper.net.minecraft.entity.boss.EntityWither;
import shordinger.wrapper.net.minecraft.entity.item.EntityArmorStand;
import shordinger.wrapper.net.minecraft.entity.item.EntityEnderPearl;
import shordinger.wrapper.net.minecraft.entity.item.EntityExpBottle;
import shordinger.wrapper.net.minecraft.entity.item.EntityFallingBlock;
import shordinger.wrapper.net.minecraft.entity.item.EntityFireworkRocket;
import shordinger.wrapper.net.minecraft.entity.item.EntityItem;
import shordinger.wrapper.net.minecraft.entity.item.EntityItemFrame;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartChest;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartCommandBlock;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartEmpty;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartFurnace;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartHopper;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartMobSpawner;
import shordinger.wrapper.net.minecraft.entity.item.EntityMinecartTNT;
import shordinger.wrapper.net.minecraft.entity.monster.EntityBlaze;
import shordinger.wrapper.net.minecraft.entity.monster.EntityCaveSpider;
import shordinger.wrapper.net.minecraft.entity.monster.EntityCreeper;
import shordinger.wrapper.net.minecraft.entity.monster.EntityElderGuardian;
import shordinger.wrapper.net.minecraft.entity.monster.EntityEnderman;
import shordinger.wrapper.net.minecraft.entity.monster.EntityEndermite;
import shordinger.wrapper.net.minecraft.entity.monster.EntityEvoker;
import shordinger.wrapper.net.minecraft.entity.monster.EntityGhast;
import shordinger.wrapper.net.minecraft.entity.monster.EntityGiantZombie;
import shordinger.wrapper.net.minecraft.entity.monster.EntityGuardian;
import shordinger.wrapper.net.minecraft.entity.monster.EntityHusk;
import shordinger.wrapper.net.minecraft.entity.monster.EntityIronGolem;
import shordinger.wrapper.net.minecraft.entity.monster.EntityMagmaCube;
import shordinger.wrapper.net.minecraft.entity.monster.EntityPigZombie;
import shordinger.wrapper.net.minecraft.entity.monster.EntityShulker;
import shordinger.wrapper.net.minecraft.entity.monster.EntitySilverfish;
import shordinger.wrapper.net.minecraft.entity.monster.EntitySkeleton;
import shordinger.wrapper.net.minecraft.entity.monster.EntitySlime;
import shordinger.wrapper.net.minecraft.entity.monster.EntitySnowman;
import shordinger.wrapper.net.minecraft.entity.monster.EntitySpider;
import shordinger.wrapper.net.minecraft.entity.monster.EntityStray;
import shordinger.wrapper.net.minecraft.entity.monster.EntityVex;
import shordinger.wrapper.net.minecraft.entity.monster.EntityVindicator;
import shordinger.wrapper.net.minecraft.entity.monster.EntityWitch;
import shordinger.wrapper.net.minecraft.entity.monster.EntityWitherSkeleton;
import shordinger.wrapper.net.minecraft.entity.monster.EntityZombie;
import shordinger.wrapper.net.minecraft.entity.monster.EntityZombieVillager;
import shordinger.wrapper.net.minecraft.entity.passive.EntityBat;
import shordinger.wrapper.net.minecraft.entity.passive.EntityChicken;
import shordinger.wrapper.net.minecraft.entity.passive.EntityCow;
import shordinger.wrapper.net.minecraft.entity.passive.EntityDonkey;
import shordinger.wrapper.net.minecraft.entity.passive.EntityHorse;
import shordinger.wrapper.net.minecraft.entity.passive.EntityMooshroom;
import shordinger.wrapper.net.minecraft.entity.passive.EntityMule;
import shordinger.wrapper.net.minecraft.entity.passive.EntityOcelot;
import shordinger.wrapper.net.minecraft.entity.passive.EntityPig;
import shordinger.wrapper.net.minecraft.entity.passive.EntityRabbit;
import shordinger.wrapper.net.minecraft.entity.passive.EntitySheep;
import shordinger.wrapper.net.minecraft.entity.passive.EntitySkeletonHorse;
import shordinger.wrapper.net.minecraft.entity.passive.EntitySquid;
import shordinger.wrapper.net.minecraft.entity.passive.EntityVillager;
import shordinger.wrapper.net.minecraft.entity.passive.EntityWolf;
import shordinger.wrapper.net.minecraft.entity.passive.EntityZombieHorse;
import shordinger.wrapper.net.minecraft.entity.player.EntityPlayer;
import shordinger.wrapper.net.minecraft.entity.player.EntityPlayerMP;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityArrow;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityDragonFireball;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityEgg;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityLargeFireball;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityPotion;
import shordinger.wrapper.net.minecraft.entity.projectile.EntitySmallFireball;
import shordinger.wrapper.net.minecraft.entity.projectile.EntitySnowball;
import shordinger.wrapper.net.minecraft.entity.projectile.EntitySpectralArrow;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityTippedArrow;
import shordinger.wrapper.net.minecraft.entity.projectile.EntityWitherSkull;
import shordinger.wrapper.net.minecraft.item.ItemStack;
import shordinger.wrapper.net.minecraft.nbt.NBTTagCompound;
import shordinger.wrapper.net.minecraft.nbt.NBTTagList;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityBrewingStand;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityChest;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityDispenser;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityDropper;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityFlowerPot;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityFurnace;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityHopper;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityMobSpawner;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityPiston;
import shordinger.wrapper.net.minecraft.tileentity.TileEntityShulkerBox;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.AddBedTileEntity;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ArmorStandSilent;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.BannerItemColor;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.BedItemColor;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.BookPagesStrictJSON;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.CookedFishIDTypo;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ElderGuardianSplit;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.EntityArmorAndHeld;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.EntityHealth;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.EntityId;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ForceVBOOn;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.HorseSaddle;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.HorseSplit;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ItemIntIDToString;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.MinecartEntityTypes;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguage;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.PaintingDirection;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.PotionItems;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.PotionWater;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.RedundantChanceTags;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.RidingToPassengers;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ShulkerBoxEntityColor;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ShulkerBoxItemColor;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ShulkerBoxTileColor;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.SignStrictJSON;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.SkeletonSplit;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.SpawnEggNames;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.SpawnerEntityTypes;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.StringToUUID;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.TileEntityId;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.TotemItemRename;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ZombieProfToType;
import shordinger.wrapper.net.minecraft.util.datafix.fixes.ZombieSplit;
import shordinger.wrapper.net.minecraft.world.chunk.storage.AnvilChunkLoader;
import shordinger.wrapper.net.minecraft.world.gen.structure.template.Template;
import shordinger.wrapper.net.minecraft.world.storage.WorldInfo;

public class DataFixesManager {

    private static void registerFixes(DataFixer fixer) {
        fixer.registerFix(FixTypes.ENTITY, new EntityArmorAndHeld());
        fixer.registerFix(FixTypes.BLOCK_ENTITY, new SignStrictJSON());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new ItemIntIDToString());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new PotionItems());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new SpawnEggNames());
        fixer.registerFix(FixTypes.ENTITY, new MinecartEntityTypes());
        fixer.registerFix(FixTypes.BLOCK_ENTITY, new SpawnerEntityTypes());
        fixer.registerFix(FixTypes.ENTITY, new StringToUUID());
        fixer.registerFix(FixTypes.ENTITY, new EntityHealth());
        fixer.registerFix(FixTypes.ENTITY, new HorseSaddle());
        fixer.registerFix(FixTypes.ENTITY, new PaintingDirection());
        fixer.registerFix(FixTypes.ENTITY, new RedundantChanceTags());
        fixer.registerFix(FixTypes.ENTITY, new RidingToPassengers());
        fixer.registerFix(FixTypes.ENTITY, new ArmorStandSilent());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new BookPagesStrictJSON());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new CookedFishIDTypo());
        fixer.registerFix(FixTypes.ENTITY, new ZombieProfToType());
        fixer.registerFix(FixTypes.OPTIONS, new ForceVBOOn());
        fixer.registerFix(FixTypes.ENTITY, new ElderGuardianSplit());
        fixer.registerFix(FixTypes.ENTITY, new SkeletonSplit());
        fixer.registerFix(FixTypes.ENTITY, new ZombieSplit());
        fixer.registerFix(FixTypes.ENTITY, new HorseSplit());
        fixer.registerFix(FixTypes.BLOCK_ENTITY, new TileEntityId());
        fixer.registerFix(FixTypes.ENTITY, new EntityId());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new BannerItemColor());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new PotionWater());
        fixer.registerFix(FixTypes.ENTITY, new ShulkerBoxEntityColor());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new ShulkerBoxItemColor());
        fixer.registerFix(FixTypes.BLOCK_ENTITY, new ShulkerBoxTileColor());
        fixer.registerFix(FixTypes.OPTIONS, new OptionsLowerCaseLanguage());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new TotemItemRename());
        fixer.registerFix(FixTypes.CHUNK, new AddBedTileEntity());
        fixer.registerFix(FixTypes.ITEM_INSTANCE, new BedItemColor());
    }

    public static DataFixer createFixer() {
        DataFixer datafixer = new DataFixer(1343);
        datafixer = new net.minecraftforge.common.util.CompoundDataFixer(datafixer);
        WorldInfo.registerFixes(datafixer);
        EntityPlayerMP.registerFixesPlayerMP(datafixer);
        EntityPlayer.registerFixesPlayer(datafixer);
        AnvilChunkLoader.registerFixes(datafixer);
        ItemStack.registerFixes(datafixer);
        Template.registerFixes(datafixer);
        Entity.registerFixes(datafixer);
        EntityArmorStand.registerFixesArmorStand(datafixer);
        EntityArrow.registerFixesArrow(datafixer);
        EntityBat.registerFixesBat(datafixer);
        EntityBlaze.registerFixesBlaze(datafixer);
        EntityCaveSpider.registerFixesCaveSpider(datafixer);
        EntityChicken.registerFixesChicken(datafixer);
        EntityCow.registerFixesCow(datafixer);
        EntityCreeper.registerFixesCreeper(datafixer);
        EntityDonkey.registerFixesDonkey(datafixer);
        EntityDragonFireball.registerFixesDragonFireball(datafixer);
        EntityElderGuardian.registerFixesElderGuardian(datafixer);
        EntityDragon.registerFixesDragon(datafixer);
        EntityEnderman.registerFixesEnderman(datafixer);
        EntityEndermite.registerFixesEndermite(datafixer);
        EntityEvoker.registerFixesEvoker(datafixer);
        EntityFallingBlock.registerFixesFallingBlock(datafixer);
        EntityFireworkRocket.registerFixesFireworkRocket(datafixer);
        EntityGhast.registerFixesGhast(datafixer);
        EntityGiantZombie.registerFixesGiantZombie(datafixer);
        EntityGuardian.registerFixesGuardian(datafixer);
        EntityHorse.registerFixesHorse(datafixer);
        EntityHusk.registerFixesHusk(datafixer);
        EntityItem.registerFixesItem(datafixer);
        EntityItemFrame.registerFixesItemFrame(datafixer);
        EntityLargeFireball.registerFixesLargeFireball(datafixer);
        EntityMagmaCube.registerFixesMagmaCube(datafixer);
        EntityMinecartChest.registerFixesMinecartChest(datafixer);
        EntityMinecartCommandBlock.registerFixesMinecartCommand(datafixer);
        EntityMinecartFurnace.registerFixesMinecartFurnace(datafixer);
        EntityMinecartHopper.registerFixesMinecartHopper(datafixer);
        EntityMinecartEmpty.registerFixesMinecartEmpty(datafixer);
        EntityMinecartMobSpawner.registerFixesMinecartMobSpawner(datafixer);
        EntityMinecartTNT.registerFixesMinecartTNT(datafixer);
        EntityMule.registerFixesMule(datafixer);
        EntityMooshroom.registerFixesMooshroom(datafixer);
        EntityOcelot.registerFixesOcelot(datafixer);
        EntityPig.registerFixesPig(datafixer);
        EntityPigZombie.registerFixesPigZombie(datafixer);
        EntityRabbit.registerFixesRabbit(datafixer);
        EntitySheep.registerFixesSheep(datafixer);
        EntityShulker.registerFixesShulker(datafixer);
        EntitySilverfish.registerFixesSilverfish(datafixer);
        EntitySkeleton.registerFixesSkeleton(datafixer);
        EntitySkeletonHorse.registerFixesSkeletonHorse(datafixer);
        EntitySlime.registerFixesSlime(datafixer);
        EntitySmallFireball.registerFixesSmallFireball(datafixer);
        EntitySnowman.registerFixesSnowman(datafixer);
        EntitySnowball.registerFixesSnowball(datafixer);
        EntitySpectralArrow.registerFixesSpectralArrow(datafixer);
        EntitySpider.registerFixesSpider(datafixer);
        EntitySquid.registerFixesSquid(datafixer);
        EntityStray.registerFixesStray(datafixer);
        EntityEgg.registerFixesEgg(datafixer);
        EntityEnderPearl.registerFixesEnderPearl(datafixer);
        EntityExpBottle.registerFixesExpBottle(datafixer);
        EntityPotion.registerFixesPotion(datafixer);
        EntityTippedArrow.registerFixesTippedArrow(datafixer);
        EntityVex.registerFixesVex(datafixer);
        EntityVillager.registerFixesVillager(datafixer);
        EntityIronGolem.registerFixesIronGolem(datafixer);
        EntityVindicator.registerFixesVindicator(datafixer);
        EntityWitch.registerFixesWitch(datafixer);
        EntityWither.registerFixesWither(datafixer);
        EntityWitherSkeleton.registerFixesWitherSkeleton(datafixer);
        EntityWitherSkull.registerFixesWitherSkull(datafixer);
        EntityWolf.registerFixesWolf(datafixer);
        EntityZombie.registerFixesZombie(datafixer);
        EntityZombieHorse.registerFixesZombieHorse(datafixer);
        EntityZombieVillager.registerFixesZombieVillager(datafixer);
        TileEntityPiston.registerFixesPiston(datafixer);
        TileEntityFlowerPot.registerFixesFlowerPot(datafixer);
        TileEntityFurnace.registerFixesFurnace(datafixer);
        TileEntityChest.registerFixesChest(datafixer);
        TileEntityDispenser.registerFixes(datafixer);
        TileEntityDropper.registerFixesDropper(datafixer);
        TileEntityBrewingStand.registerFixesBrewingStand(datafixer);
        TileEntityHopper.registerFixesHopper(datafixer);
        BlockJukebox.registerFixesJukebox(datafixer);
        TileEntityMobSpawner.registerFixesMobSpawner(datafixer);
        TileEntityShulkerBox.registerFixesShulkerBox(datafixer);
        registerFixes(datafixer);
        return datafixer;
    }

    public static NBTTagCompound processItemStack(IDataFixer fixer, NBTTagCompound compound, int version, String key) {
        if (compound.hasKey(key, 10)) {
            compound.setTag(key, fixer.process(FixTypes.ITEM_INSTANCE, compound.getCompoundTag(key), version));
        }

        return compound;
    }

    public static NBTTagCompound processInventory(IDataFixer fixer, NBTTagCompound compound, int version, String key) {
        if (compound.hasKey(key, 9)) {
            NBTTagList nbttaglist = compound.getTagList(key, 10);

            for (int i = 0; i < nbttaglist.tagCount(); ++i) {
                nbttaglist.set(i, fixer.process(FixTypes.ITEM_INSTANCE, nbttaglist.getCompoundTagAt(i), version));
            }
        }

        return compound;
    }
}
